// Package key defines the key event types and modifier constants used by the
// Kite terminal UI engine.
//
// # Key Struct
//
// Key carries the pressed key's rune Code, the optional printable Text,
// a Mod bitmask for modifiers (Ctrl, Alt, Shift, Meta, Hyper, Super,
// CapsLock, NumLock, ScrollLock), and an IsRepeat flag for auto-repeat
// events generated by the OS.
//
// # Key Matching
//
// MatchString(s ...string) reports whether k matches any of the given
// string expressions. Expressions use "+" to separate modifiers and key
// names, e.g. "ctrl+c", "alt+enter", "shift+up". The mapping between
// string names and rune constants is defined in the stringKeyType map.
//
// # Constants
//
// Key codes are split into directional keys (Up, Down, Left, Right),
// function keys (F1–F63), keypad keys, media keys, modifier keys, and
// ASCII control codes (C0). The Kitty keyboard extension constants are
// also included when available.
//
// Example:
//
//	if k.MatchString("ctrl+c") {
//	    // handle copy
//	}
package key
