package key

import (
	"strings"
	"unicode"
	"unicode/utf8"
)

type Key struct {
	// Text contains the actual characters received. This usually the same as
	// [Key.Code]. When [Key.Text] is non-empty, it indicates that the key
	// pressed represents printable character(s).
	Text string

	// Code represents the key pressed.
	// E.g., [KeyTab], [KeyEnter], [KeyArrowUp], etc.
	Code rune

	// IsRepeat indicates whether this key event is a repeat (i.e., the key is being held
	// down and the event is generated by the system's key repeat mechanism). When true, this
	// event should be treated as a repeat of the previous key event, and may be ignored by
	// some applications that only want to respond to the initial key press.
	IsRepeat bool

	// Mod is a bitmask of modifier keys (e.g., Ctrl, Alt, Shift) that were held down when the key event occurred. The specific modifier keys and their corresponding bit values are defined by the application or library handling the key events.
	Mod Mod
}

func (k Key) MatchString(s ...string) bool {
	for _, str := range s {
		if keyMatchString(k, str) {
			return true
		}
	}
	return false
}

func keyMatchString(k Key, s string) bool {
	var (
		mod  Mod
		code rune
		text string
	)

	for part := range strings.SplitSeq(s, "+") {
		switch {
		case strings.EqualFold(part, "ctrl"):
			mod |= ModCtrl
		case strings.EqualFold(part, "alt"):
			mod |= ModAlt
		case strings.EqualFold(part, "shift"):
			mod |= ModShift
		case strings.EqualFold(part, "meta"):
			mod |= ModMeta
		case strings.EqualFold(part, "super"):
			mod |= ModSuper
		case strings.EqualFold(part, "hyper"):
			mod |= ModHyper
		case strings.EqualFold(part, "capslock"):
			mod |= ModCapsLock
		case strings.EqualFold(part, "numlock"):
			mod |= ModNumLock
		case strings.EqualFold(part, "scrolllock"):
			mod |= ModScrollLock
		default:
			if k, ok := stringKeyType[strings.ToLower(part)]; ok {
				code = k
			} else {
				if utf8.RuneCountInString(part) == 1 {
					code, _ = utf8.DecodeRuneInString(part)
				} else {
					code = KeyExtended
					text = part
				}

			}
		}
	}

	smod := mod &^ (ModShift | ModCapsLock)
	if smod == 0 && text == "" && unicode.IsPrint(k.Code) {
		if mod&ModShift != 0 || mod&ModCapsLock != 0 {
			text = string(unicode.ToUpper(k.Code))
		} else {
			text = string(code)
		}
	}

	return (k.Mod == mod && k.Code == code) || (k.Text == text && text != "")
}

var stringKeyType = map[string]rune{
	"enter":     KeyEnter,
	"tab":       KeyTab,
	"backspace": KeyBackspace,
	"escape":    KeyEscape,
	"esc":       KeyEscape,
	"space":     KeySpace,
	"up":        KeyUp,
	"down":      KeyDown,
	"left":      KeyLeft,
	"right":     KeyRight,
	"begin":     KeyBegin,
	"find":      KeyFind,
	"insert":    KeyInsert,
	"delete":    KeyDelete,
	"select":    KeySelect,
	"pgup":      KeyPgUp,
	"pgdown":    KeyPgDown,
	"home":      KeyHome,
	"end":       KeyEnd,
	"kpenter":   KeyKpEnter,
	"kpequal":   KeyKpEqual,
	"kpmul":     KeyKpMultiply,
	"kpplus":    KeyKpPlus,
	"kpcomma":   KeyKpComma,
	"kpminus":   KeyKpMinus,
	"kpperiod":  KeyKpDecimal,
	"kpdiv":     KeyKpDivide,
	"kp0":       KeyKp0,
	"kp1":       KeyKp1,
	"kp2":       KeyKp2,
	"kp3":       KeyKp3,
	"kp4":       KeyKp4,
	"kp5":       KeyKp5,
	"kp6":       KeyKp6,
	"kp7":       KeyKp7,
	"kp8":       KeyKp8,
	"kp9":       KeyKp9,

	// Kitty keyboard extension
	"kpsep":    KeyKpSep,
	"kpup":     KeyKpUp,
	"kpdown":   KeyKpDown,
	"kpleft":   KeyKpLeft,
	"kpright":  KeyKpRight,
	"kppgup":   KeyKpPgUp,
	"kppgdown": KeyKpPgDown,
	"kphome":   KeyKpHome,
	"kpend":    KeyKpEnd,
	"kpinsert": KeyKpInsert,
	"kpdelete": KeyKpDelete,
	"kpbegin":  KeyKpBegin,

	"f1":  KeyF1,
	"f2":  KeyF2,
	"f3":  KeyF3,
	"f4":  KeyF4,
	"f5":  KeyF5,
	"f6":  KeyF6,
	"f7":  KeyF7,
	"f8":  KeyF8,
	"f9":  KeyF9,
	"f10": KeyF10,
	"f11": KeyF11,
	"f12": KeyF12,
	"f13": KeyF13,
	"f14": KeyF14,
	"f15": KeyF15,
	"f16": KeyF16,
	"f17": KeyF17,
	"f18": KeyF18,
	"f19": KeyF19,
	"f20": KeyF20,
	"f21": KeyF21,
	"f22": KeyF22,
	"f23": KeyF23,
	"f24": KeyF24,
	"f25": KeyF25,
	"f26": KeyF26,
	"f27": KeyF27,
	"f28": KeyF28,
	"f29": KeyF29,
	"f30": KeyF30,
	"f31": KeyF31,
	"f32": KeyF32,
	"f33": KeyF33,
	"f34": KeyF34,
	"f35": KeyF35,
	"f36": KeyF36,
	"f37": KeyF37,
	"f38": KeyF38,
	"f39": KeyF39,
	"f40": KeyF40,
	"f41": KeyF41,
	"f42": KeyF42,
	"f43": KeyF43,
	"f44": KeyF44,
	"f45": KeyF45,
	"f46": KeyF46,
	"f47": KeyF47,
	"f48": KeyF48,
	"f49": KeyF49,
	"f50": KeyF50,
	"f51": KeyF51,
	"f52": KeyF52,
	"f53": KeyF53,
	"f54": KeyF54,
	"f55": KeyF55,
	"f56": KeyF56,
	"f57": KeyF57,
	"f58": KeyF58,
	"f59": KeyF59,
	"f60": KeyF60,
	"f61": KeyF61,
	"f62": KeyF62,
	"f63": KeyF63,

	// Kitty keyboard extension
	"capslock":         KeyCapsLock,
	"scrolllock":       KeyScrollLock,
	"numlock":          KeyNumLock,
	"printscreen":      KeyPrintScreen,
	"pause":            KeyPause,
	"menu":             KeyMenu,
	"mediaplay":        KeyMediaPlay,
	"mediapause":       KeyMediaPause,
	"mediaplaypause":   KeyMediaPlayPause,
	"mediareverse":     KeyMediaReverse,
	"mediastop":        KeyMediaStop,
	"mediafastforward": KeyMediaFastForward,
	"mediarewind":      KeyMediaRewind,
	"medianext":        KeyMediaNext,
	"mediaprev":        KeyMediaPrev,
	"mediarecord":      KeyMediaRecord,
	"lowervol":         KeyLowerVol,
	"raisevol":         KeyRaiseVol,
	"mute":             KeyMute,
	"leftshift":        KeyLeftShift,
	"leftalt":          KeyLeftAlt,
	"leftctrl":         KeyLeftCtrl,
	"leftsuper":        KeyLeftSuper,
	"lefthyper":        KeyLeftHyper,
	"leftmeta":         KeyLeftMeta,
	"rightshift":       KeyRightShift,
	"rightalt":         KeyRightAlt,
	"rightctrl":        KeyRightCtrl,
	"rightsuper":       KeyRightSuper,
	"righthyper":       KeyRightHyper,
	"rightmeta":        KeyRightMeta,
	"isolevel3shift":   KeyIsoLevel3Shift,
	"isolevel5shift":   KeyIsoLevel5Shift,
}

var keyTypeString = map[rune]string{
	KeyEnter:      "enter",
	KeyTab:        "tab",
	KeyBackspace:  "backspace",
	KeyEscape:     "esc",
	KeySpace:      "space",
	KeyUp:         "up",
	KeyDown:       "down",
	KeyLeft:       "left",
	KeyRight:      "right",
	KeyBegin:      "begin",
	KeyFind:       "find",
	KeyInsert:     "insert",
	KeyDelete:     "delete",
	KeySelect:     "select",
	KeyPgUp:       "pgup",
	KeyPgDown:     "pgdown",
	KeyHome:       "home",
	KeyEnd:        "end",
	KeyKpEnter:    "enter",
	KeyKpEqual:    "equal",
	KeyKpMultiply: "mul",
	KeyKpPlus:     "plus",
	KeyKpComma:    "comma",
	KeyKpMinus:    "minus",
	KeyKpDecimal:  "period",
	KeyKpDivide:   "div",
	KeyKp0:        "0",
	KeyKp1:        "1",
	KeyKp2:        "2",
	KeyKp3:        "3",
	KeyKp4:        "4",
	KeyKp5:        "5",
	KeyKp6:        "6",
	KeyKp7:        "7",
	KeyKp8:        "8",
	KeyKp9:        "9",

	// Kitty keyboard extension
	KeyKpSep:    "sep",
	KeyKpUp:     "up",
	KeyKpDown:   "down",
	KeyKpLeft:   "left",
	KeyKpRight:  "right",
	KeyKpPgUp:   "pgup",
	KeyKpPgDown: "pgdown",
	KeyKpHome:   "home",
	KeyKpEnd:    "end",
	KeyKpInsert: "insert",
	KeyKpDelete: "delete",
	KeyKpBegin:  "begin",

	KeyF1:  "f1",
	KeyF2:  "f2",
	KeyF3:  "f3",
	KeyF4:  "f4",
	KeyF5:  "f5",
	KeyF6:  "f6",
	KeyF7:  "f7",
	KeyF8:  "f8",
	KeyF9:  "f9",
	KeyF10: "f10",
	KeyF11: "f11",
	KeyF12: "f12",
	KeyF13: "f13",
	KeyF14: "f14",
	KeyF15: "f15",
	KeyF16: "f16",
	KeyF17: "f17",
	KeyF18: "f18",
	KeyF19: "f19",
	KeyF20: "f20",
	KeyF21: "f21",
	KeyF22: "f22",
	KeyF23: "f23",
	KeyF24: "f24",
	KeyF25: "f25",
	KeyF26: "f26",
	KeyF27: "f27",
	KeyF28: "f28",
	KeyF29: "f29",
	KeyF30: "f30",
	KeyF31: "f31",
	KeyF32: "f32",
	KeyF33: "f33",
	KeyF34: "f34",
	KeyF35: "f35",
	KeyF36: "f36",
	KeyF37: "f37",
	KeyF38: "f38",
	KeyF39: "f39",
	KeyF40: "f40",
	KeyF41: "f41",
	KeyF42: "f42",
	KeyF43: "f43",
	KeyF44: "f44",
	KeyF45: "f45",
	KeyF46: "f46",
	KeyF47: "f47",
	KeyF48: "f48",
	KeyF49: "f49",
	KeyF50: "f50",
	KeyF51: "f51",
	KeyF52: "f52",
	KeyF53: "f53",
	KeyF54: "f54",
	KeyF55: "f55",
	KeyF56: "f56",
	KeyF57: "f57",
	KeyF58: "f58",
	KeyF59: "f59",
	KeyF60: "f60",
	KeyF61: "f61",
	KeyF62: "f62",
	KeyF63: "f63",

	// Kitty keyboard extension
	KeyCapsLock:         "capslock",
	KeyScrollLock:       "scrolllock",
	KeyNumLock:          "numlock",
	KeyPrintScreen:      "printscreen",
	KeyPause:            "pause",
	KeyMenu:             "menu",
	KeyMediaPlay:        "mediaplay",
	KeyMediaPause:       "mediapause",
	KeyMediaPlayPause:   "mediaplaypause",
	KeyMediaReverse:     "mediareverse",
	KeyMediaStop:        "mediastop",
	KeyMediaFastForward: "mediafastforward",
	KeyMediaRewind:      "mediarewind",
	KeyMediaNext:        "medianext",
	KeyMediaPrev:        "mediaprev",
	KeyMediaRecord:      "mediarecord",
	KeyLowerVol:         "lowervol",
	KeyRaiseVol:         "raisevol",
	KeyMute:             "mute",
	KeyLeftShift:        "leftshift",
	KeyLeftAlt:          "leftalt",
	KeyLeftCtrl:         "leftctrl",
	KeyLeftSuper:        "leftsuper",
	KeyLeftHyper:        "lefthyper",
	KeyLeftMeta:         "leftmeta",
	KeyRightShift:       "rightshift",
	KeyRightAlt:         "rightalt",
	KeyRightCtrl:        "rightctrl",
	KeyRightSuper:       "rightsuper",
	KeyRightHyper:       "righthyper",
	KeyRightMeta:        "rightmeta",
	KeyIsoLevel3Shift:   "isolevel3shift",
	KeyIsoLevel5Shift:   "isolevel5shift",
}

const (
	// KeyExtended is a special key code used to signify that a key event
	// contains multiple runes.
	KeyExtended = unicode.MaxRune + 1
)

// Special key symbols.
const (

	// Special keys.

	KeyUp rune = KeyExtended + iota + 1
	KeyDown
	KeyRight
	KeyLeft
	KeyBegin
	KeyFind
	KeyInsert
	KeyDelete
	KeySelect
	KeyPgUp
	KeyPgDown
	KeyHome
	KeyEnd

	// Keypad keys.

	KeyKpEnter
	KeyKpEqual
	KeyKpMultiply
	KeyKpPlus
	KeyKpComma
	KeyKpMinus
	KeyKpDecimal
	KeyKpDivide
	KeyKp0
	KeyKp1
	KeyKp2
	KeyKp3
	KeyKp4
	KeyKp5
	KeyKp6
	KeyKp7
	KeyKp8
	KeyKp9

	//nolint:godox
	// The following are keys defined in the Kitty keyboard protocol.
	// TODO: Investigate the names of these keys.

	KeyKpSep
	KeyKpUp
	KeyKpDown
	KeyKpLeft
	KeyKpRight
	KeyKpPgUp
	KeyKpPgDown
	KeyKpHome
	KeyKpEnd
	KeyKpInsert
	KeyKpDelete
	KeyKpBegin

	// Function keys.

	KeyF1
	KeyF2
	KeyF3
	KeyF4
	KeyF5
	KeyF6
	KeyF7
	KeyF8
	KeyF9
	KeyF10
	KeyF11
	KeyF12
	KeyF13
	KeyF14
	KeyF15
	KeyF16
	KeyF17
	KeyF18
	KeyF19
	KeyF20
	KeyF21
	KeyF22
	KeyF23
	KeyF24
	KeyF25
	KeyF26
	KeyF27
	KeyF28
	KeyF29
	KeyF30
	KeyF31
	KeyF32
	KeyF33
	KeyF34
	KeyF35
	KeyF36
	KeyF37
	KeyF38
	KeyF39
	KeyF40
	KeyF41
	KeyF42
	KeyF43
	KeyF44
	KeyF45
	KeyF46
	KeyF47
	KeyF48
	KeyF49
	KeyF50
	KeyF51
	KeyF52
	KeyF53
	KeyF54
	KeyF55
	KeyF56
	KeyF57
	KeyF58
	KeyF59
	KeyF60
	KeyF61
	KeyF62
	KeyF63

	//nolint:godox
	// The following are keys defined in the Kitty keyboard protocol.
	// TODO: Investigate the names of these keys.

	KeyCapsLock
	KeyScrollLock
	KeyNumLock
	KeyPrintScreen
	KeyPause
	KeyMenu

	KeyMediaPlay
	KeyMediaPause
	KeyMediaPlayPause
	KeyMediaReverse
	KeyMediaStop
	KeyMediaFastForward
	KeyMediaRewind
	KeyMediaNext
	KeyMediaPrev
	KeyMediaRecord

	KeyLowerVol
	KeyRaiseVol
	KeyMute

	KeyLeftShift
	KeyLeftAlt
	KeyLeftCtrl
	KeyLeftSuper
	KeyLeftHyper
	KeyLeftMeta
	KeyRightShift
	KeyRightAlt
	KeyRightCtrl
	KeyRightSuper
	KeyRightHyper
	KeyRightMeta
	KeyIsoLevel3Shift
	KeyIsoLevel5Shift

	// Special names in C0.

	KeyBackspace = rune(0x7f)
	KeyTab       = rune(0x09)
	KeyEnter     = rune(0x0d)
	KeyReturn    = KeyEnter
	KeyEscape    = rune(0x1b)
	KeyEsc       = KeyEscape

	// Special names in G0.

	KeySpace = rune(0x20)
)
